// utils/mockData.js — All 19 robots from Excel file

export const ROBOTS = [
  {
    id: 'optimus-gen2',
    image: null,
    name: 'Optimus Gen 2',
    maker: 'Tesla',
    country: 'USA',
    countryCode: 'US',
    price: '$20k–$30k target',
    priceNum: 25000,
    availability: 'Internal Deploy (1,000+ units)',
    availClass: 'available',
    score: 75,
    dof: '28 (body)',
    height: "168 cm (5'6\")",
    weight: '57 kg',
    speed: '1.2 m/s',
    battery: '~2 hr',
    ai: 'Tesla FSD Neural Net',
    hand: 'Actuated',
    deploy: 'Internal / Tesla Factories',
    payload: '20 kg',
    tags: ['usa', 'industrial'],
    scoreBreakdown: { dexterity: 72, ai: 80, value: 75, hype: 85, realworld: 70, build: 80 },
    verdict: "Tesla's second-generation Optimus quietly doing real work inside Tesla factories. The internal deployment milestone proves the concept.",
    pros: ['1,000+ units deployed', 'Tesla manufacturing scale', 'FSD AI advantage'],
    cons: ['Not commercially available', 'Slower than Gen 3', 'Limited public data'],
    excerpt: 'Quietly doing real work inside Tesla factories — Optimus Gen 2 is proof that the concept works at scale.',
  },
  {
    id: 'optimus-gen3',
    image: null,
    name: 'Optimus Gen 3',
    maker: 'Tesla',
    country: 'USA',
    countryCode: 'US',
    price: '$20k–$30k target',
    priceNum: 25000,
    availability: 'Production start Summer 2026',
    availClass: 'soon',
    score: 88,
    dof: '28 body + 22 DOF/hand (50 actuators)',
    height: "173 cm (5'8\")",
    weight: '57 kg',
    speed: '~2.2 m/s',
    battery: '2.3 kWh pack',
    ai: 'Tesla FSD Neural Net',
    hand: '22 DOF/hand',
    deploy: 'Industrial / Tesla Factories',
    payload: '20 kg',
    tags: ['flagship', 'usa', 'industrial'],
    scoreBreakdown: { dexterity: 90, ai: 95, value: 72, hype: 98, realworld: 88, build: 94 },
    verdict: "The most hyped robot in history, and arguably the most capable AI-driven humanoid yet. Tesla's FSD neural net gives Optimus a generalization edge.",
    pros: ['Best-in-class AI integration', 'Tesla manufacturing scale', '50 total actuators', 'Best hand dexterity'],
    cons: ['Production start Summer 2026', 'Price TBC', 'Limited to Tesla factories'],
    excerpt: "Tesla's most ambitious product yet brings FSD-level AI to a body that could redefine factory automation.",
  },
  {
    id: 'figure-02',
    image: null,
    name: 'Figure 02',
    maker: 'Figure AI',
    country: 'USA',
    countryCode: 'US',
    price: '$130,000',
    priceNum: 130000,
    availability: 'Commercial Pilot (BMW)',
    availClass: 'beta',
    score: 85,
    dof: '41',
    height: "170 cm (5'7\")",
    weight: '60 kg',
    speed: '1.2 m/s',
    battery: '~5 hr',
    ai: 'Figure Neural Net + OpenAI',
    hand: 'Dexterous',
    deploy: 'BMW Factories',
    payload: '20 kg',
    tags: ['usa', 'industrial', 'openai'],
    scoreBreakdown: { dexterity: 88, ai: 87, value: 55, hype: 85, realworld: 80, build: 88 },
    verdict: "Figure 02 proved humanoids can do real factory work. BMW didn't partner with Figure by accident.",
    pros: ['BMW deployment proven', 'OpenAI integration', 'Premium build quality', '41 DOF'],
    cons: ['$130,000 price', 'Superseded by Figure 03', 'Slower speed'],
    excerpt: 'Figure 02 proved humanoids can do real factory work. Its BMW deployment changed the industry conversation.',
  },
  {
    id: 'figure-03',
    image: null,
    name: 'Figure 03',
    maker: 'Figure AI',
    country: 'USA',
    countryCode: 'US',
    price: '$130,000',
    priceNum: 130000,
    availability: 'Pilot Production (BotQ ramp)',
    availClass: 'beta',
    score: 91,
    dof: '48+',
    height: '165–168 cm',
    weight: '55–60 kg',
    speed: '1.5 m/s',
    battery: '~6 hr',
    ai: 'Figure Neural Net + OpenAI',
    hand: '16-DOF custom',
    deploy: 'BMW Factories',
    payload: '20 kg',
    tags: ['premium', 'usa', 'industrial', 'openai'],
    scoreBreakdown: { dexterity: 94, ai: 90, value: 58, hype: 88, realworld: 82, build: 91 },
    verdict: 'Figure 03 has the most human-like hands in the industry. 48+ DOF and proven at BMW — this is the industrial benchmark.',
    pros: ['48+ DOF', 'Most dexterous hands', 'BMW deployment proven', 'Longest battery (6 hr)'],
    cons: ['$130,000', 'Supply constrained', 'Industrial only'],
    excerpt: 'With 48+ DOF and a BMW partnership, Figure 03 is making the strongest case for humanoid robots in real factory environments.',
  },
  {
    id: '1x-neo',
    image: null,
    name: 'NEO',
    maker: '1X Technologies',
    country: 'Norway',
    countryCode: 'EU',
    price: '$20,000 / $499 mo',
    priceNum: 20000,
    availability: 'Shipping (Home / Consumer)',
    availClass: 'available',
    score: 87,
    dof: '~26 body + 22 DOF/hand',
    height: "167 cm (5'6\")",
    weight: '30 kg',
    speed: '3.5 m/s',
    battery: '2–4 hr',
    ai: 'OpenAI-backed LLM',
    hand: '22 DOF/hand',
    deploy: 'Home / Consumer',
    payload: '25 kg carry / 68 kg lift',
    tags: ['home', 'safe', 'openai', 'available'],
    scoreBreakdown: { dexterity: 82, ai: 88, value: 78, hype: 80, realworld: 85, build: 82 },
    verdict: 'Shipping to homes now. 1X NEO is the first humanoid robot you can actually buy for your house today.',
    pros: ['Shipping now to consumers', 'Fastest in class (3.5 m/s)', 'Lightest (30 kg)', 'OpenAI partnership', '68 kg lift capacity'],
    cons: ['Norway-based support', 'Short battery (2–4 hr)', 'Less industrial utility'],
    excerpt: 'Built to live alongside humans, 1X NEO is shipping to homes today — the first truly consumer humanoid.',
  },
  {
    id: 'atlas-electric',
    image: null,
    name: 'Atlas (Electric)',
    maker: 'Boston Dynamics',
    country: 'USA',
    countryCode: 'US',
    price: '~$420,000',
    priceNum: 420000,
    availability: 'Deploying (Hyundai / Google DeepMind)',
    availClass: 'beta',
    score: 93,
    dof: '56',
    height: "152 cm (5'0\")",
    weight: '89 kg',
    speed: '2.5 m/s',
    battery: '~4 hr (hot-swap)',
    ai: 'Proprietary Hyundai AI',
    hand: 'Actuated 3-finger',
    deploy: 'R&D / Hyundai Factories',
    payload: '50 kg peak / 25–30 kg sustained',
    tags: ['research', 'usa', 'most-capable'],
    scoreBreakdown: { dexterity: 95, ai: 85, value: 20, hype: 92, realworld: 78, build: 98 },
    verdict: "The gold standard of robot locomotion. Atlas redefined what's physically possible with 56 DOF and 50 kg payload.",
    pros: ['56 DOF — most in class', '50 kg peak payload', 'Best locomotion ever built', 'Hyundai + Google DeepMind backing'],
    cons: ['~$420,000', 'Not for sale publicly', '89 kg weight', 'Limited battery'],
    excerpt: 'Atlas Electric is the benchmark every other humanoid is secretly being compared against. 56 DOF. 50 kg payload. Unmatched.',
  },
  {
    id: 'agibot-a2',
    image: null,
    name: 'AgiBot A2',
    maker: 'AgiBot',
    country: 'China',
    countryCode: 'CN',
    price: '~$100k–$190k',
    priceNum: 145000,
    availability: 'Production',
    availClass: 'available',
    score: 82,
    dof: '40+',
    height: "169 cm (5'6\")",
    weight: '69 kg',
    speed: '3.3 m/s',
    battery: '~2 hr',
    ai: 'Custom LLM',
    hand: 'Dexterous',
    deploy: 'Manufacturing / Logistics',
    payload: '15 kg',
    tags: ['china', 'available', 'logistics'],
    scoreBreakdown: { dexterity: 85, ai: 80, value: 60, hype: 70, realworld: 84, build: 83 },
    verdict: "AgiBot A2 is China's fast-production humanoid. 3.3 m/s walking speed ties for fastest in class.",
    pros: ['3.3 m/s walking speed', '40+ DOF', 'In production now', 'Manufacturing-proven'],
    cons: ['Price unverified', 'Short battery (2 hr)', 'Less Western support'],
    excerpt: "AgiBot quietly built one of China's most capable production humanoids — and it's shipping today.",
  },
  {
    id: 'fourier-gr2',
    image: null,
    name: 'Fourier GR-2',
    maker: 'Fourier Intelligence',
    country: 'China',
    countryCode: 'CN',
    price: '$150,000+',
    priceNum: 150000,
    availability: 'Production',
    availClass: 'available',
    score: 84,
    dof: '53',
    height: "175 cm (5'9\")",
    weight: '63 kg',
    speed: '1.4 m/s',
    battery: '~2 hr',
    ai: 'FourierGPT',
    hand: '12-DOF bionic',
    deploy: 'Medical / Research',
    payload: '10–15 kg',
    tags: ['china', 'medical', 'high-dof', 'available'],
    scoreBreakdown: { dexterity: 92, ai: 72, value: 60, hype: 62, realworld: 76, build: 86 },
    verdict: 'Fourier GR-2 wins on DOF with 53 total joints, making it ideal for medical and research applications.',
    pros: ['53 DOF', 'Best for medical use', "Tallest at 175 cm", 'In production'],
    cons: ['$150,000+', 'Short battery (2 hr)', 'Slow speed (1.4 m/s)'],
    excerpt: "Fourier's GR-2 offers 53 DOF and medical-grade precision — the humanoid built for healthcare.",
  },
  {
    id: 'apptronik-apollo',
    image: null,
    name: 'Apollo',
    maker: 'Apptronik',
    country: 'USA',
    countryCode: 'US',
    price: '$50k target (~$200k+ now)',
    priceNum: 200000,
    availability: 'Mass Production Ramp (Mercedes-Benz)',
    availClass: 'beta',
    score: 90,
    dof: '71',
    height: "173 cm (5'8\")",
    weight: '73 kg',
    speed: '0.9–2.1 m/s',
    battery: '~4 hr',
    ai: 'Google DeepMind',
    hand: '5-finger',
    deploy: 'Industrial / Mercedes-Benz',
    payload: '25 kg',
    tags: ['usa', 'google', 'industrial'],
    scoreBreakdown: { dexterity: 88, ai: 90, value: 60, hype: 82, realworld: 85, build: 88 },
    verdict: 'Apollo has the most DOF of any commercial robot (71), Google DeepMind AI, and a Mercedes-Benz deployment.',
    pros: ['71 DOF — highest commercial', 'Google DeepMind AI', 'Mercedes-Benz deployment', 'NASA heritage team', '25 kg payload'],
    cons: ['Currently ~$200k+', 'Heaviest (73 kg)', 'Speed variable'],
    excerpt: 'With 71 DOF and Google DeepMind powering its brain, Apollo is the most articulated commercial humanoid on the market.',
  },
  {
    id: 'unitree-r1',
    image: null,
    name: 'R1',
    maker: 'Unitree Robotics',
    country: 'China',
    countryCode: 'CN',
    price: '$4,900–$5,900',
    priceNum: 5900,
    availability: 'Pre-order / Shipping 2026',
    availClass: 'soon',
    score: 72,
    dof: '24',
    height: "~100 cm (3'3\")",
    weight: '25–29 kg',
    speed: '2.5 m/s',
    battery: '~1 hr',
    ai: 'Custom LLM',
    hand: 'Dexterous',
    deploy: 'General / Research',
    payload: '2 kg',
    tags: ['value', 'china', 'cheapest'],
    scoreBreakdown: { dexterity: 65, ai: 72, value: 98, hype: 78, realworld: 68, build: 75 },
    verdict: 'The cheapest humanoid robot in the world at $4,900. Nothing else comes close to this price.',
    pros: ['Cheapest humanoid: $4,900', 'Shipping 2026', 'Lightest at 25–29 kg'],
    cons: ['Only 100 cm tall', '2 kg payload', '1 hr battery', 'Not full-size'],
    excerpt: 'At $4,900, Unitree R1 is the most affordable humanoid robot ever made — period.',
  },
  {
    id: 'ubtech-walker-s2',
    image: null,
    name: 'Walker S2',
    maker: 'UBTECH Robotics',
    country: 'China',
    countryCode: 'CN',
    price: '~$90k–$160k',
    priceNum: 125000,
    availability: 'Commercial / Mass Production Delivery',
    availClass: 'available',
    score: 86,
    dof: '52',
    height: "176 cm (5'9\")",
    weight: '73 kg',
    speed: '2.0 m/s',
    battery: '24/7 (autonomous hot-swap)',
    ai: 'Custom AI',
    hand: 'Dexterous',
    deploy: 'Industrial / Manufacturing',
    payload: '15 kg',
    tags: ['china', 'available', 'industrial'],
    scoreBreakdown: { dexterity: 85, ai: 82, value: 65, hype: 75, realworld: 86, build: 87 },
    verdict: 'Walker S2 is the only humanoid with autonomous hot-swap battery — meaning it can run 24/7 without stopping.',
    pros: ['24/7 operation via hot-swap battery', '52 DOF', 'Tallest at 176 cm', 'Mass production delivery'],
    cons: ['$90k–$160k', '73 kg weight', 'Less brand awareness in West'],
    excerpt: "UBTECH's Walker S2 is the only humanoid that never needs to stop — autonomous battery hot-swap means 24/7 operation.",
  },
  {
    id: 'agility-digit',
    image: null,
    name: 'Digit',
    maker: 'Agility Robotics',
    country: 'USA',
    countryCode: 'US',
    price: '$100k–$250k',
    priceNum: 175000,
    availability: 'Fleet Commercial / RaaS (Amazon, Toyota)',
    availClass: 'available',
    score: 89,
    dof: '30',
    height: "175 cm (5'9\")",
    weight: '63–64 kg',
    speed: '1.5–5.4 m/s',
    battery: 'Up to 8 hr',
    ai: 'Agility AI',
    hand: 'Grippers',
    deploy: 'Warehouse / Logistics (Amazon)',
    payload: '16–22 kg',
    tags: ['usa', 'available', 'logistics', 'amazon'],
    scoreBreakdown: { dexterity: 80, ai: 85, value: 58, hype: 80, realworld: 92, build: 88 },
    verdict: 'Digit is the most commercially proven humanoid robot. Amazon and Toyota deployments make it the real-world logistics leader.',
    pros: ['Amazon deployment at scale', 'Longest battery (8 hr)', 'Fastest top speed (5.4 m/s)', 'RaaS model available'],
    cons: ['$100k–$250k', 'Gripper hands only', 'Limited DOF (30)'],
    excerpt: 'With Amazon and Toyota deployments at scale, Digit is the most commercially proven humanoid robot in the world.',
  },
  {
    id: 'unitree-g1',
    image: null,
    name: 'G1',
    maker: 'Unitree Robotics',
    country: 'China',
    countryCode: 'CN',
    price: '$13,500',
    priceNum: 13500,
    availability: 'Production (5,500+ units shipped)',
    availClass: 'available',
    score: 83,
    dof: '23–43',
    height: "127–132 cm (4'2\")",
    weight: '35 kg',
    speed: '2.0 m/s',
    battery: '~2 hr (swappable)',
    ai: 'Custom LLM',
    hand: 'Dexterous',
    deploy: 'Research / Education',
    payload: '2–3 kg',
    tags: ['china', 'available', 'value', 'research'],
    scoreBreakdown: { dexterity: 80, ai: 78, value: 92, hype: 72, realworld: 80, build: 82 },
    verdict: 'Unitree G1 is the best-selling humanoid robot of 2025–2026 with 5,500+ units shipped. At $13,500 it is the value king for research.',
    pros: ['5,500+ units shipped', '$13,500 price', 'Swappable battery', 'Up to 43 DOF'],
    cons: ['Only 127–132 cm tall', '2–3 kg payload', 'Research-focused'],
    excerpt: 'With 5,500+ units shipped, Unitree G1 is the best-selling humanoid robot in history — at just $13,500.',
  },
  {
    id: 'neura-4ne1',
    image: null,
    name: '4NE1 Gen',
    maker: 'NEURA Robotics',
    country: 'Germany',
    countryCode: 'EU',
    price: '€98k (~$105k) / €60k fleet',
    priceNum: 105000,
    availability: 'Pre-production (late 2026)',
    availClass: 'soon',
    score: 82,
    dof: '~40+',
    height: "180 cm (5'11\")",
    weight: '~75 kg',
    speed: '~1.5 m/s',
    battery: 'N/A (not disclosed)',
    ai: 'Custom AI',
    hand: 'Dexterous',
    deploy: 'Industrial / Service',
    payload: '15–20 kg carry / 100 kg lift',
    tags: ['eu', 'industrial', 'german-engineering'],
    scoreBreakdown: { dexterity: 82, ai: 80, value: 65, hype: 78, realworld: 78, build: 88 },
    verdict: "NEURA's 4NE1 is the tallest humanoid at 180 cm with an extraordinary 100 kg lift capacity. German engineering applied to robotics.",
    pros: ['Tallest: 180 cm', '100 kg lift capacity', 'German engineering', 'Fleet pricing: €60k'],
    cons: ['Pre-production (late 2026)', 'Battery not disclosed', 'Speed not impressive'],
    excerpt: "At 180 cm tall with 100 kg lift capacity, NEURA's 4NE1 is Germany's answer to the humanoid race.",
  },
  {
    id: 'unitree-h2',
    image: null,
    name: 'H2',
    maker: 'Unitree Robotics',
    country: 'China',
    countryCode: 'CN',
    price: '$29,900+',
    priceNum: 29900,
    availability: 'Shipping (April 2026)',
    availClass: 'available',
    score: 80,
    dof: '31',
    height: "180 cm (5'11\")",
    weight: '~60 kg',
    speed: '~2.0 m/s',
    battery: '~2 hr (swappable)',
    ai: 'Custom LLM',
    hand: 'Dexterous',
    deploy: 'Research / Industrial',
    payload: '~25 kg',
    tags: ['china', 'available', 'full-size'],
    scoreBreakdown: { dexterity: 78, ai: 76, value: 85, hype: 70, realworld: 78, build: 80 },
    verdict: 'Unitree H2 is a full-size 180 cm humanoid shipping now at $29,900 — the best value full-size robot on the market.',
    pros: ['Full-size: 180 cm', 'Shipping April 2026', '$29,900 price', '25 kg payload', 'Swappable battery'],
    cons: ['2 hr battery', 'Less DOF than competitors', 'Unitree brand perception'],
    excerpt: 'A full-size humanoid at $29,900, shipping now. Unitree H2 redefines value in the full-size segment.',
  },
  {
    id: 'sanctuary-phoenix',
    image: null,
    name: 'Phoenix (Gen 7)',
    maker: 'Sanctuary AI',
    country: 'Canada',
    countryCode: 'EU',
    price: '~$40,000 (est.)',
    priceNum: 40000,
    availability: 'Pilot (Magna International)',
    availClass: 'beta',
    score: 85,
    dof: '75 total (20 DOF/hand)',
    height: "170 cm (5'7\")",
    weight: '70 kg',
    speed: '1.2 m/s',
    battery: '~4 hr',
    ai: 'Carbon AI (proprietary)',
    hand: '20 DOF/hand',
    deploy: 'Industrial (Magna International)',
    payload: '25 kg',
    tags: ['canada', 'industrial', 'dexterous-hands'],
    scoreBreakdown: { dexterity: 92, ai: 84, value: 72, hype: 76, realworld: 82, build: 85 },
    verdict: 'Phoenix Gen 7 has 20 DOF per hand — among the most dexterous in the world. Magna International deployment proves industrial viability.',
    pros: ['20 DOF/hand (industry-leading)', '75 total DOF', 'Magna International deployed', '~$40k est. price'],
    cons: ['Canada-only currently', 'Slow speed (1.2 m/s)', '70 kg weight'],
    excerpt: "With 20 DOF per hand and a Magna International deployment, Sanctuary's Phoenix is the dexterity champion.",
  },
  {
    id: 'xpeng-iron',
    image: null,
    name: 'IRON (Next-Gen)',
    maker: 'Xpeng (XPEV)',
    country: 'China',
    countryCode: 'CN',
    price: '~$150,000 (est.)',
    priceNum: 150000,
    availability: 'Factory Pilot → Mass prod. end 2026',
    availClass: 'soon',
    score: 79,
    dof: '82 body (22 DOF/hand)',
    height: '173–178 cm',
    weight: '~70 kg',
    speed: 'N/A (not disclosed)',
    battery: 'Solid-state (not disclosed)',
    ai: 'Xpeng AI',
    hand: '22 DOF/hand',
    deploy: 'Factory / Industrial',
    payload: 'N/A (not disclosed)',
    tags: ['china', 'high-dof', 'solid-state-battery'],
    scoreBreakdown: { dexterity: 88, ai: 78, value: 55, hype: 82, realworld: 70, build: 80 },
    verdict: "Xpeng's IRON brings 82 total DOF and solid-state battery technology. Xpeng's EV expertise applied to robotics.",
    pros: ['82 DOF body', '22 DOF/hand', 'Solid-state battery', "Xpeng EV tech backing"],
    cons: ['Most specs not disclosed', '~$150,000 est.', 'Mass production end 2026'],
    excerpt: "Xpeng applies its EV expertise to robotics with 82 DOF and a solid-state battery — specs that could reshape the competition.",
  },
  {
    id: 'unitree-h1',
    image: null,
    name: 'H1 / H1-2',
    maker: 'Unitree Robotics',
    country: 'China',
    countryCode: 'CN',
    price: '$90,000 / $128,900',
    priceNum: 90000,
    availability: 'Production (Research)',
    availClass: 'available',
    score: 78,
    dof: '19–27',
    height: "180 cm (5'11\")",
    weight: '47 kg',
    speed: '3.3 m/s',
    battery: '~1.5 hr',
    ai: 'Custom LLM',
    hand: 'Standard',
    deploy: 'Research / Education',
    payload: '~10 kg',
    tags: ['china', 'available', 'research', 'fast'],
    scoreBreakdown: { dexterity: 72, ai: 74, value: 70, hype: 68, realworld: 75, build: 80 },
    verdict: "H1 blazed the trail for Unitree's humanoid line. At 3.3 m/s it's among the fastest, but lower DOF limits manipulation.",
    pros: ['3.3 m/s walking speed', '180 cm full-size', 'Lightest full-size (47 kg)', 'Proven reliability'],
    cons: ['Low DOF (19–27)', '$90k–$129k price', 'Short battery (1.5 hr)'],
    excerpt: "Unitree H1 blazed the trail — 3.3 m/s, 180 cm, and the robot that proved China could compete at the top.",
  },
  {
    id: 'agibot-x2',
    image: null,
    name: 'Agibot X2',
    maker: 'AGIBOT Innovation',
    country: 'China',
    countryCode: 'CN',
    price: '$25,000–$40,000',
    priceNum: 32500,
    availability: 'Commercial / Available',
    availClass: 'available',
    score: 78,
    dof: '25',
    height: "131 cm (4'3\")",
    weight: '35 kg',
    speed: '1.8 m/s',
    battery: '2 hours',
    ai: 'Custom AI',
    hand: 'Dexterous',
    deploy: 'General / Commercial',
    payload: '3 kg',
    tags: ['china', 'available', 'compact'],
    scoreBreakdown: { dexterity: 75, ai: 72, value: 82, hype: 65, realworld: 75, build: 78 },
    verdict: 'Agibot X2 is a compact, affordable humanoid shipping today. At $25k–$40k it sits in a useful price-performance sweet spot.',
    pros: ['Available now', '$25k–$40k price', 'Compact (131 cm)', '35 kg lightweight'],
    cons: ['Only 131 cm tall', '3 kg payload', '2 hr battery', 'Limited DOF (25)'],
    excerpt: 'Compact, affordable, and shipping now — Agibot X2 fills the gap between toy robots and industrial-grade humanoids.',
  },
]

export const REVIEWS = [
  {
    id: 'review-optimus-gen3',
    robotId: 'optimus-gen3',
    robotName: 'Optimus Gen 3',
    score: 88,
    readTime: '12 min',
    date: '2026-05-01',
    author: 'Marcus Chen',
    authorTitle: 'Senior Robot Analyst',
    excerpt: "Tesla's Gen 3 Optimus represents a quantum leap in AI-driven humanoid robotics. The FSD neural network adaptation for physical tasks is nothing short of remarkable.",
    pros: ['Unmatched AI generalization', 'Tesla manufacturing advantage', '50 total actuators', 'Proven in factory setting'],
    cons: ['Production start Summer 2026', 'Heavy (57kg)', 'Limited to Tesla factories'],
    verdict: 'Tesla Optimus Gen 3 is the most complete humanoid robot package — if you can wait for Summer 2026.',
    tags: ['flagship', 'AI', 'industrial'],
    featured: true,
  },
  {
    id: 'review-atlas',
    robotId: 'atlas-electric',
    robotName: 'Atlas (Electric)',
    score: 93,
    readTime: '14 min',
    date: '2026-04-18',
    author: 'Sarah Kim',
    authorTitle: 'Hardware Engineer',
    excerpt: "Boston Dynamics' electric Atlas is the most mechanically impressive humanoid ever built. 56 DOF and 50 kg payload put it in a class of its own — but at $420,000, almost nobody can buy one.",
    pros: ['56 DOF — class-leading', '50 kg peak payload', 'Best locomotion ever', 'Hot-swap battery'],
    cons: ['~$420,000', 'Not for public sale', '89 kg heavy'],
    verdict: 'The gold standard. If you can get one.',
    tags: ['research', 'premium', 'locomotion'],
    featured: false,
  },
  {
    id: 'review-digit',
    robotId: 'agility-digit',
    robotName: 'Digit',
    score: 89,
    readTime: '11 min',
    date: '2026-04-05',
    author: 'Alex Rivera',
    authorTitle: 'Industrial Automation Expert',
    excerpt: "Amazon chose Digit. Toyota chose Digit. When two of the world's largest logistics operations independently pick the same robot, that's not a coincidence — that's a verdict.",
    pros: ['Amazon deployment at scale', '8 hr battery life', '5.4 m/s top speed', 'RaaS model available'],
    cons: ['$100k–$250k', 'Gripper hands only', 'Limited DOF (30)'],
    verdict: "The most commercially proven humanoid. Amazon's choice.",
    tags: ['logistics', 'industrial', 'proven'],
    featured: false,
  },
]

export const NEWS = [
  {
    id: 'news-1',
    category: 'Launches',
    categoryColor: 'teal',
    title: 'Unitree R1 Now Shipping Globally at $5,900',
    excerpt: 'Unitree Robotics has confirmed global shipping of its R1 humanoid robot at $4,900–$5,900, marking a historic price point for the humanoid robot industry.',
    date: '2026-05-08',
    readTime: '4 min',
    source: 'RoboPulse Staff',
  },
  {
    id: 'news-2',
    category: 'Funding',
    categoryColor: 'gold',
    title: 'Figure AI Raises Additional $675M at $39.5B Valuation',
    excerpt: 'Figure AI has closed an additional $675M funding round at a $39.5B valuation, accelerating BotQ production ramp for Figure 03.',
    date: '2026-05-05',
    readTime: '6 min',
    source: 'RoboPulse Staff',
  },
  {
    id: 'news-3',
    category: 'Deployments',
    categoryColor: 'purple',
    title: 'Honor Robot Sets Humanoid Half-Marathon Record in Beijing',
    excerpt: 'A humanoid robot completed a half-marathon in Beijing, setting a new record for humanoid endurance running and showcasing dramatic improvements in locomotion.',
    date: '2026-04-29',
    readTime: '5 min',
    source: 'RoboPulse Staff',
  },
  {
    id: 'news-4',
    category: 'Launches',
    categoryColor: 'teal',
    title: 'AgiBot A2 Hits 5,100+ Units — Most Shipped by Any Maker',
    excerpt: 'AgiBot has become the highest-volume humanoid robot manufacturer with over 5,100 A2 units shipped, overtaking previous leaders in total deployed fleet size.',
    date: '2026-04-22',
    readTime: '5 min',
    source: 'RoboPulse Staff',
  },
  {
    id: 'news-5',
    category: 'Launches',
    categoryColor: 'teal',
    title: '1X NEO Now Shipping to Homes at $20K or $499/mo',
    excerpt: '1X Technologies has opened consumer orders for the NEO humanoid robot at $20,000 outright or $499 per month, making it the first truly consumer-available humanoid.',
    date: '2026-04-15',
    readTime: '4 min',
    source: 'RoboPulse Staff',
  },
  {
    id: 'news-6',
    category: 'Deployments',
    categoryColor: 'purple',
    title: 'Boston Dynamics Atlas Wins Best Robot at CES 2026',
    excerpt: 'The electric Atlas took home Best Robot at CES 2026, with judges citing its 56 DOF, 50 kg payload, and Hyundai factory deployments as decisive factors.',
    date: '2026-04-10',
    readTime: '4 min',
    source: 'RoboPulse Staff',
  },
  {
    id: 'news-7',
    category: 'Launches',
    categoryColor: 'teal',
    title: 'Tesla Optimus Gen 3 Production Confirmed for Summer 2026',
    excerpt: 'Tesla has confirmed production start for Optimus Gen 3 in Summer 2026, with the upgraded 50-actuator system expected to roll out across all Gigafactory locations.',
    date: '2026-04-08',
    readTime: '5 min',
    source: 'RoboPulse Staff',
  },
]

export const PRICE_TRACKER = [
  { id: 'unitree-r1',      name: 'Unitree R1',    image: null,       current: 5900,   sixMonthAgo: 9900,   change: -40.4, trend: 'down' },
  { id: 'unitree-g1',      name: 'Unitree G1',    image: null,       current: 13500,  sixMonthAgo: 16000,  change: -15.6, trend: 'down' },
  { id: 'optimus-gen3',    name: 'Optimus Gen 3', image: null,     current: 25000,  sixMonthAgo: 30000,  change: -16.7, trend: 'down' },
  { id: 'figure-03',       name: 'Figure 03',     image: null,        current: 130000, sixMonthAgo: 130000, change: 0,     trend: 'flat' },
  { id: 'apptronik-apollo',name: 'Apollo',        image: null, current: 200000, sixMonthAgo: 200000, change: 0,     trend: 'flat' },
  { id: 'agility-digit',   name: 'Digit',         image: null,    current: 175000, sixMonthAgo: 200000, change: -12.5, trend: 'down' },
]

export const CATEGORIES = [
  { id: 'reviews',    name: 'Reviews',     icon: '⭐', description: 'In-depth expert robot reviews',      count: 24,  color: 'teal'   },
  { id: 'comparisons',name: 'Comparisons',icon: '⚖️', description: 'Head-to-head robot battles',         count: 18,  color: 'purple' },
  { id: 'news',       name: 'News',        icon: '📡', description: 'Breaking robotics industry news',    count: 142, color: 'pink'   },
  { id: 'guides',     name: 'Guides',      icon: '📘', description: 'Buyer guides and explainers',        count: 31,  color: 'gold'   },
  { id: 'database',   name: 'Database',    icon: '🗄️', description: 'Full robot specs and data',          count: 40,  color: 'teal'   },
  { id: 'us-vs-china',name: 'US vs China', icon: '🌐', description: 'Geopolitical robot analysis',        count: 22,  color: 'pink'   },
]

export const GUIDES = [
  { id: 'buyers-guide-2026',    type: 'buyers',    title: "Complete Humanoid Robot Buying Guide 2026",          description: "Everything you need to know before spending $5,900–$420,000 on a humanoid robot.", readTime: '25 min', tags: ['essential','buying'] },
  { id: 'industrial-guide',     type: 'buyers',    title: 'Industrial Robotics Procurement Guide',              description: 'How to evaluate, procure, and deploy humanoid robots at enterprise scale.',          readTime: '30 min', tags: ['enterprise','industrial'] },
  { id: 'home-robotics-guide',  type: 'buyers',    title: 'Are Home Robots Ready in 2026?',                    description: "An honest look at which humanoid robots are actually ready for home use today.",    readTime: '15 min', tags: ['home','consumer'] },
  { id: 'china-vs-us-buyers',   type: 'buyers',    title: "Chinese vs American Robots: The Buyer's Perspective",description: 'Tariffs, support, quality, and geopolitics — what matters when choosing.',           readTime: '18 min', tags: ['geopolitics','comparison'] },
  { id: 'how-humanoids-work',   type: 'explainer', title: 'How Humanoid Robots Actually Work',                 description: 'From actuators to neural nets — a complete technical explainer for non-engineers.',  readTime: '20 min', tags: ['technical','explainer'] },
  { id: 'ai-in-robots',         type: 'explainer', title: 'AI in Humanoid Robots: LLMs, VLMs, and World Models',description: 'The AI stack powering today\'s humanoid revolution explained clearly.',               readTime: '16 min', tags: ['AI','technical'] },
  { id: 'dof-explained',        type: 'explainer', title: 'Degrees of Freedom Explained',                      description: 'Why DOF matters, what it means in practice, and how to compare robots fairly.',    readTime: '8 min',  tags: ['technical','basics'] },
  { id: 'battery-life-truth',   type: 'explainer', title: 'The Truth About Robot Battery Life',                description: "Manufacturers always exaggerate. Here's how to interpret real-world battery specs.", readTime: '10 min', tags: ['specs','practical'] },
  { id: 'manufacturing-dive',   type: 'deep-dive', title: 'Manufacturing Robots: The $50B Opportunity',        description: 'Deep analysis of humanoid robots in automotive, electronics, and manufacturing.',     readTime: '35 min', tags: ['industry','manufacturing'] },
  { id: 'china-deep-dive',      type: 'deep-dive', title: "China's Robotics Strategy: The Full Picture",       description: 'How China went from copier to leader in humanoid robotics in under five years.',     readTime: '40 min', tags: ['china','geopolitics'] },
  { id: 'healthcare-robots',    type: 'deep-dive', title: 'Humanoids in Healthcare: Promise vs Reality',       description: "From elder care to surgical assist — what's real, what's hype, what's coming.",      readTime: '28 min', tags: ['healthcare','medical'] },
  { id: 'investment-landscape', type: 'deep-dive', title: 'The $165B Robotics Investment Landscape',           description: "Who's funding what, at what valuations, and where the smart money is flowing.",      readTime: '32 min', tags: ['investing','market'] },
]

export const TICKER_ITEMS = [
  '▶ Unitree R1 now shipping globally at $5,900',
  '▶ Tesla Optimus Gen 3 production start: Summer 2026',
  '▶ Figure raises additional $675M at $39.5B valuation',
  '▶ Honor robot sets humanoid half-marathon record in Beijing',
  '▶ AgiBot A2 hits 5,100+ units shipped — most by any maker',
  '▶ 1X NEO shipping to homes NOW at $20K or $499/mo',
  '▶ Boston Dynamics Atlas wins Best Robot at CES 2026',
]

export const SCORE_METRICS = [
  { key: 'dexterity', label: 'Dexterity',           description: 'Hand and finger articulation, precision tasks', color: 'teal'   },
  { key: 'ai',        label: 'AI / Intelligence',   description: 'Language, vision, task reasoning capabilities', color: 'purple' },
  { key: 'value',     label: 'Value for Money',     description: 'Price-to-performance ratio vs market',          color: 'gold'   },
  { key: 'hype',      label: 'Hype Ratio',          description: 'Marketing vs actual delivered capability',      color: 'pink'   },
  { key: 'realworld', label: 'Real-world Usefulness',description: 'Practical deployed utility today',             color: 'teal'   },
  { key: 'build',     label: 'Build Quality',       description: 'Hardware engineering, durability, finish',      color: 'purple' },
]